languages:
  Ruby: true
exclude_paths:
  - "app/assets/javascripts/lib/underscore.js"
  - "app/assets/javascripts/lib/backbone.js"
  - "app/assets/javascripts/lib/backbone.paginator.js"
  - "app/assets/javascripts/lib/js.cookie.js"
  - "spec/**/*_spec.rb"
  - "db/migrate/20170107151912_rpush_2_0_0_updates.rb"
  - "db/migrate/20170107151911_add_rpush.rb"
