languages:
  Ruby: true
exclude_paths:
- "spec/controllers/api/sessions_controller_spec.rb"
- "spec/controllers/api/signups_controller_spec.rb"
- "spec/routing/api/sessions_routing_spec.rb"
- "spec/routing/api/signups_routing_spec.rb"
- "spec/policies/api_key_policy_spec.rb"
