sources:
  bundler: true
  npm: false

allowed:
  - 'mit'
  - 'apache-2.0'

reviewed:
  bundler:
    - 'activerecord'
    - 'activerecord-nulldb-adapter'
    - 'ansi'
    - 'bcrypt'
    - 'concurrent-ruby'
    - 'elasticsearch'
    - 'elasticsearch-api'
    - 'elasticsearch-transport'
    - 'ffi'
    - 'method_source'
    - 'nokogiri'
    - 'omniauth'
    - 'pg'
    - 'pg_query'
    - 'puma'
    - 'rack'
    - 'rack-health'
    - 'swagger-blocks'
    - 'tilt'
