AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'Capfile'
    - 'db/schema.rb'
    - 'bin/brakeman'
    - 'bin/rspec'
    - 'bin/rubocop'
    - 'bin/setup'
    - 'config/initializers/assets.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/new_framework_defaults.rb'
    - 'config/initializers/rack-cors.rb'
    - 'config/initializers/wrap_parameters.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: true
  Max: 80

Style/Documentation:
  Enabled: false

# Enable this cop later
Style/FrozenStringLiteralComment:
  Enabled: false
