AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'Capfile'
    - 'db/schema.rb'
    - 'bin/brakeman'
    - 'bin/rspec'
    - 'bin/rubocop'
    - 'bin/setup'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: true
  Max: 80

Style/Documentation:
  Enabled: false

# Enable this cop later
Style/FrozenStringLiteralComment:
  Enabled: false
