require: rubocop-thread_safety
require: rubocop-rspec

inherit_from: .rubocop_todo.yml
inherit_from: .rubocop_general.yml

Style/StringLiterals:
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'app/controllers/api/docs_controller.rb'
    - 'app/documentation/**/*.rb'
    - 'config/routes.rb'
    - 'db/schema.rb'
    - 'spec/**/*.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/documentation/**/*.rb'

# Bug in rubocop-rspec cop
RSpec/FilePath:
  Exclude:
    - 'spec/routing/**/*.rb'

# Possibly bug in rubocop-rspec cop
RSpec/ExampleLength:
  Exclude:
    - 'spec/routing/**/*.rb'

RSpec/MultipleDescribes:
  Exclude:
    - 'spec/policies/**/*.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/schema.rb'

Layout/AlignParameters:
  Exclude:
    - 'bin/brakeman'
    - 'bin/bundle-audit'
    - 'bin/cap'
    - 'bin/capify'
    - 'bin/consistency_fail'
    - 'bin/license_finder'
    - 'bin/mdl'
    - 'bin/mry'
    - 'bin/puma'
    - 'bin/pumactl'
    - 'bin/rpush'
    - 'bin/rspec'
    - 'bin/rubocop'
    - 'bin/rubycritic'
    - 'bin/sidekiq'
    - 'bin/sidekiqctl'
    - 'bin/squasher'

Naming/FileName:
  Exclude:
    - 'config/initializers/rack-cors.rb'
    - 'spec/support/shoulda-matchers.rb'

Style/WordArray:
  Exclude:
    - 'config/spring.rb'

Style/PercentLiteralDelimiters:
  Exclude:
    - 'config/spring.rb'
