AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - 'Capfile'
  Exclude:
    - 'Capfile'
    - 'db/schema.rb'
    - 'bin/brakeman'
    - 'bin/rspec'
    - 'bin/rubocop'
    - 'bin/setup'

Rails:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

# Enable this cop later
Style/FrozenStringLiteralComment:
  Enabled: false
