language: ruby
sudo: false
cache: bundler
bundler_args: --jobs=3 --retry=3 --without development
rvm:
  - 2.4.1

before_script:
  - ln -sf database.yml.sqlite3 config/database.yml
  - bundle exec rake db:create db:migrate

script:
  - bundle exec rake
  - bundle exec codeclimate-test-reporter
