version: '3.7'

volumes:
  postresql-data:
  redis-data:

services:
  nginx:
    image: 'nginx:1.14.2'

  redis:
    image: 'redis:5.0.4'
    volumes:
      - "redis-data:/data"

  memcached:
    image: 'memcached:1.5.12'

  postgresql:
    image: 'postgres:11.2'
    volumes:
      - "postresql-data:/var/lib/postgresql/data"

  prometheus:
    image: 'prom/prometheus:v2.8.0'
    depends_on:
      - backend

  grafana:
    image: 'grafana/grafana:6.0.2'
    depends_on:
      - prometheus

  elasticsearch:
    image: 'elasticsearch:6.6.2'

#  sentry:
#    image: ''
#    depends_on:
#      - postgresql
#      - redis

  app: &app
    build: .
    restart: 'no'
    env_file: .env_docker

  backend:
    <<: *app
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - memcached
      - postgresql
      - elasticsearch
#      - sentry

  sidekiq:
    <<: *app
    command: bundle exec sidekiq
    depends_on:
      - redis
      - memcached
      - postgresql
      - elasticsearch
#      - sentry
