swagger: '2.0'
info:
  title: 'EveMonk back-end API'
  description: 'EveMonk back-end REST API documentation'
  version: '0.1.0'
host: localhost:3000
schemes:
  - http
  - https
basePath: /api
consumes:
  - application/json
  - application/x-www-form-urlencoded
produces:
  - application/json
tags:
  - name: signups
    description: Signups operations
  - name: sessions
    description: Session operations
  - name: api keys
    description: API Keys operations

paths:
  /signups:
    post:
      summary: Signup
      description: |
        Signup endpoint.
      parameters:
        - name: user[email]
          in: formData
          description: User email
          required: true
          type: string
        - name: user[password]
          in: formData
          description: User password
          required: true
          type: string
          format: password
        - name: user[password_confirmation]
          in: formData
          description: User password confirmation
          required: true
          type: string
          format: password
      tags:
        - signups
      responses:
        200:
          description: Account created
          schema:
            $ref: '#/definitions/OutputSecureToken'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /sessions:
    post:
      summary: Get user auth token
      description: |
        Signin user and return user with token.
      parameters:
        - name: session[email]
          in: formData
          description: User email
          required: true
          type: string
        - name: session[password]
          in: formData
          description: User password
          type: string
          format: password
      tags:
        - sessions
      responses:
        200:
          description: Response with User model with token
          schema:
            $ref: '#/definitions/OutputUser'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /api_keys:
    get:
      summary: Get list of User API Keys
      description: |
        Get list of User API Keys.
      parameters:
        - name: Authorization
          in: header
          description: 'User auth token. Example: Token token="value"'
          default: Token token="ACCESS_TOKEN"
          required: true
          type: string
        - name: page
          in: query
          description: Page number for pagination
          type: integer
          format: int64
      tags:
        - api keys
      responses:
        200:
          description: API Keys collection
          schema:
            $ref: '#/definitions/OutputApiKeyCollection'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

    post:
      summary: Add EveOnline API Key
      description: |
        Create api key for user.
      parameters:
        - name: Authorization
          in: header
          description: 'User auth token. Example: Token token="value"'
          default: Token token="ACCESS_TOKEN"
          required: true
          type: string
        - name: api_key[key_id]
          in: formData
          description: EveOnline API Key ID
          required: true
          type: string
        - name: api_key[v_code]
          in: formData
          description: EveOnline API Key code
          required: true
          type: string
      tags:
        - api keys
      responses:
        200:
          description: API Key response
          schema:
            $ref: '#/definitions/OutputApiKey'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /api_keys/{id}:
    get:
      summary: Get EveOnline API Key
      description: |
        Get EveOnine API Key by ID.
      parameters:
        - name: Authorization
          in: header
          description: 'User auth token. Example: Token token="value"'
          default: Token token="ACCESS_TOKEN"
          required: true
          type: string
        - name: id
          in: path
          description: API Key ID
          required: true
          type: integer
          format: int64
      tags:
        - api keys
      responses:
        200:
          description: API Key response
          schema:
            $ref: '#/definitions/OutputApiKey'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: API Key not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

    delete:
      summary: Delete EveOnline API Key
      description: |
        Delete EveOnine API Key by ID.
      parameters:
        - name: Authorization
          in: header
          description: 'User auth token. Example: Token token="value"'
          default: Token token="ACCESS_TOKEN"
          required: true
          type: string
        - name: id
          in: path
          description: API Key ID
          required: true
          type: integer
          format: int64
      tags:
        - api keys
      responses:
        200:
          description: API Key removed
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: API Key not found
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

    put:
      summary: Update EveOnline API Key
      description: |
        Update EveOnine API Key by ID.
      parameters:
        - name: Authorization
          in: header
          description: 'User auth token. Example: Token token="value"'
          default: Token token="ACCESS_TOKEN"
          required: true
          type: string
        - name: id
          in: path
          description: API Key ID
          required: true
          type: integer
          format: int64
        - name: api_key[key_id]
          in: formData
          description: EveOnline API Key ID
          required: true
          type: string
        - name: api_key[v_code]
          in: formData
          description: EveOnline API Key code
          required: true
          type: string
      tags:
        - api keys
      responses:
        200:
          description: API Key response
          schema:
            $ref: '#/definitions/OutputApiKey'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: API Key not found
        422:
          description: Unprocessable Entity
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

    patch:
      summary: Update EveOnline API Key
      description: |
        Update EveOnine API Key by ID.
      parameters:
        - name: Authorization
          in: header
          description: 'User auth token. Example: Token token="value"'
          default: Token token="ACCESS_TOKEN"
          required: true
          type: string
        - name: id
          in: path
          description: API Key ID
          required: true
          type: integer
          format: int64
        - name: api_key[key_id]
          in: formData
          description: EveOnline API Key ID
          required: false
          type: string
        - name: api_key[v_code]
          in: formData
          description: EveOnline API Key code
          required: false
          type: string
      tags:
        - api keys
      responses:
        200:
          description: API Key response
          schema:
            $ref: '#/definitions/OutputApiKey'
        401:
          description: Unauthorized
        403:
          description: Forbidden
        404:
          description: API Key not found
        422:
          description: Unprocessable Entity
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  OutputUser:
    required:
      - id
      - email
      - token
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: User ID. e.g. "42"
      email:
        type: string
        description: User email. e.g. "me@example.com"
      token:
        type: string
        description: User auth token. e.g. "AAkoMiLatQHMngyuUU1vnh5b"

  OutputApiKey:
    required:
      - id
      - key_id
      - v_code
      - created_at
      - updated_at
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: APIKey ID. e.g. "123"
      key_id:
        type: integer
        format: int64
        description: APIKey Key ID. e.g. "1234567"
      v_code:
        type: string
        description: APIKey Code. e.g. "4a66f384d27c59af02f16746d480689ee3674b58a0d822518eb57bddd4e904f7"
      created_at:
        type: string
        description: Created at in ISO8601 format
      updated_at:
        type: string
        description: Updated at in ISO8601 format

  OutputApiKeyCollection:
    required:
      - collection
      - total_pages
      - current_page
    type: object
    properties:
      collection:
        type: array
        items:
          $ref: '#/definitions/OutputApiKey'
      total_pages:
        type: integer
        format: int64
        description: Total pages counter
      current_page:
        type: integer
        format: int64
        description: Current page number

  OutputSecureToken:
    required:
      - id
      - token
      - created_at
      - updated_at
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: SecureToken ID. e.g. "123"
      token:
        type: string
        description: User secure auth token. e.g. "AAkoMiLatQHMngyuUU1vnh5b"
      created_at:
        type: string
        description: Created at in ISO8601 format
      updated_at:
        type: string
        description: Updated at in ISO8601 format

  Error:
    type: object
    properties:
      errors:
        type: array
        items:
          type: string
          description: Error description
