swagger: '2.0'
info:
  title: EveMonk back-end API
  description: EveMonk back-end REST API documentation
  version: 1.0.0
  termsOfService: http://evemonk.com/terms
  contact:
    name: Igor Zubkov
    url: http://evemonk.com/support
    email: igor.zubkov@gmail.com
host: evemonk.com
schemes:
  - http
  - https
basePath: /api
consumes:
  - application/json
  - application/x-www-form-urlencoded
produces:
  - application/json
tags:
  - name: sessions
    description: Session operations
  - name: profile
    description: Profile operations

paths:
  /sessions:
    get:
      summary: Get all user sessions
      description: Get all user sessions.
      parameters:
        - name: Authorization
          in: header
          description: 'User auth token. Example: Bearer AAkoMiLatQHMngyuUU1vnh5b'
          default: Bearer ACCESS_TOKEN
          required: true
          type: string
        - name: page
          in: query
          description: Page number for pagination
          type: integer
          format: int64
      tags:
        - sessions
      responses:
        '200':
          description: Response with sessions collection
          schema:
            $ref: '#/definitions/OutputSessionCollection'
        '406':
          description: Content type not supported
        '401':
          description: Unauthorized

  /sessions/{id}:
    delete:
      summary: End session
      description: End session
      parameters:
        - name: Authorization
          in: header
          description: 'User auth token. Example: Bearer AAkoMiLatQHMngyuUU1vnh5b'
          default: Bearer ACCESS_TOKEN
          required: true
          type: string
        - name: id
          in: path
          description: Session ID
          required: true
          type: integer
          format: int64
      tags:
        - sessions
      responses:
        '200':
          description: Success
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Session not found

definitions:
  OutputSessionWithoutToken:
    required:
      - id
      - name
      - created_at
      - updated_at
    type: object
    properties:
      id:
        type: integer
        format: int64
        description: Session ID
      name:
        type: string
        description: Session name
      created_at:
        type: string
        description: Created at in ISO8601 format
      updated_at:
        type: string
        description: Updated at in ISO8601 format
    example:
      id: 123
      name: 'My Computer'
      created_at: '2016-12-12T18:35:59Z'
      updated_at: '2016-12-12T18:36:10Z'

  OutputSessionCollection:
    required:
      - collection
      - total_pages
      - current_page
    type: object
    properties:
      collection:
        type: array
        items:
          $ref: '#/definitions/OutputSessionWithoutToken'
      total_pages:
        type: integer
        format: int64
        description: Total pages counter
      current_page:
        type: integer
        format: int64
        description: Current page number

  Error:
    type: object
    properties:
      errors:
        type: array
        items:
          type: string
          description: Error description
