require: rubocop-thread_safety
require: rubocop-rspec
require: rubocop-performance

inherit_from:
  - .rubocop_general.yml
  - .rubocop_rspec.yml
  - .rubocop-thread_safety.yml

# Bug in rubocop-rspec cop
RSpec/FilePath:
  Exclude:
    - 'spec/routing/**/*.rb'

# Possibly bug in rubocop-rspec cop
RSpec/ExampleLength:
  Exclude:
    - 'spec/routing/**/*.rb'

RSpec/MultipleDescribes:
  Exclude:
    - 'spec/policies/**/*.rb'

Style/MethodCallWithArgsParentheses:
  Exclude:
    - 'db/migrate/*.rb'
    - 'spec/**/*_spec.rb'
